#!/bin/sh

set -e

if [ "x" = "x${1}" ]; then
        echo "Usage: $0 <date>"
        exit 1
fi

. ./fetch.cfg

ts=`date -d "$1" \+%s`
if curl -k -X GET -H "Authorization: Bearer ${token}" ${apiurl}/last?ts=${ts} -o getlast.json; then

        id=`jq -r '.[0].id' < getlast.json`
        ut=`jq -r '.[0].ut' < getlast.json`

        dn="dump-"`date -d @${ut} +"%Y-%m-%dT%H:%M:%S%z"`

        echo "id=$id; dn=$dn"

        if [ "x" != "x${id}" ]; then
                if curl -k -X GET -H "Authorization: Bearer ${token}" ${apiurl}/get/${id} -o ${dn}.xml; then
                        xmllint  --format ${dn}.xml >${dn}-f.xml
                fi
        fi

fi
